
version: '3'

services:
  db:
    container_name: postgres-challenge
    image: postgres:12
    restart: unless-stopped
    volumes:
      - postgres-challenge-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
    networks:
      - app-connect

  nodejs-challenge:
    container_name: nodejs-challenge
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - db
    networks:
      - app-connect
    ports:
      - '3333:3333'
    environment: 
      DB_HOST: db

volumes:
  postgres-challenge-data:

networks:
  app-connect:
      driver: bridge